- name: datatypes
  hosts: localhosts
  vars:
   NAME: PALSON
   Skills: 
   - java
   - spring
   - aws
   - ansible
   
   Experience:
     java : 1
     spring: 1
     aws: 2
     ansible: 1

    Trainer: true

  tasks: 
  - name: to print key value pair
    ansible.builtin.debug:
      msg: "name: {{NAME}}"
  
  - name: print list
    ansible.builtin.debug:
      msg: "skills: {{Skills}}"
  
  - name: print map
    ansible.buitlin.debug:
      msg: "experience: {{Experience}}"
  
  - name: print boolean
    ansible.buitlin.debug:
      msg: "is he trainer: {{Trainer}}"