- name: install and uninstall loops
  hosts: localhost
  become: yes
  tasks: 
  - name: install and unistall packages
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop: 
    - {name: 'java', state: 'present'}
    - {name: 'git', state: 'absent'}